import { eq, and } from "drizzle-orm";
import { db } from "@/server/db/client";
import { artifacts, auditLog, tasks } from "@/server/db/schema";
import { audit } from "@/server/auth/audit";
import { makeRunContext } from "@/server/worker/runContext";
import {
  doc,
  heading,
  paragraph,
  strong,
  text,
  rule,
  panel,
  bulletList,
  extractSummary,
} from "./adf";

/**
 * Post a Jira comment summarising a Plan amendment triggered by a prior
 * Review's AMEND/REWRITE verdict. Called by spawnAgent.finalize() when a
 * run with amendFromReview=true completes successfully.
 *
 * Best-effort — logs a warning + audit row on failure but doesn't throw.
 */
export async function postAmendmentComment(runId: string, taskId: string): Promise<void> {
  const task = db.select().from(tasks).where(eq(tasks.id, taskId)).get();
  if (!task) return;

  // Per-task creds drive Jira identity for this comment.
  const ctx = makeRunContext(task.ownerId);
  if (!ctx.jiraClient) return;

  // Latest Plan + last Review that preceded this amend (the one whose
  // findings drove the amendment). We want the Review that was around
  // BEFORE this Plan run — so the most recent non-current Review.
  const latestPlan = db
    .select({
      filename: artifacts.filename,
      markdown: artifacts.markdown,
      runId: artifacts.runId,
    })
    .from(artifacts)
    .where(and(eq(artifacts.taskId, taskId), eq(artifacts.kind, "plan")))
    .orderBy(artifacts.createdAt)
    .all()
    .reverse()[0];
  if (!latestPlan) return;

  const latestReview = db
    .select({ filename: artifacts.filename, markdown: artifacts.markdown })
    .from(artifacts)
    .where(and(eq(artifacts.taskId, taskId), eq(artifacts.kind, "review")))
    .orderBy(artifacts.createdAt)
    .all()
    .reverse()[0];

  const priorVerdict = latestReview
    ? extractSummary(latestReview.markdown, "review").verdict
    : null;

  const planSummary = extractSummary(latestPlan.markdown, "plan");

  const body = doc([
    heading(3, "Plan amended from Review findings"),
    paragraph(
      text("The Plan has been regenerated to address findings from the previous Review"),
      priorVerdict ? text(` (verdict: `) : text("."),
      priorVerdict ? strong(priorVerdict) : text(""),
      priorVerdict ? text(").") : text(""),
    ),
    priorVerdict && priorVerdict !== "READY"
      ? panel(
          priorVerdict === "REWRITE" ? "error" : "warning",
          paragraph(
            text("Prior Review verdict was "),
            strong(priorVerdict),
            text(" — the amendment targets the issues raised."),
          ),
        )
      : paragraph(""),
    rule(),
    paragraph(strong("Revised Plan file: "), text(latestPlan.filename)),
    planSummary.intro ? paragraph(planSummary.intro) : paragraph(""),
    planSummary.sections.length > 0
      ? bulletList(planSummary.sections)
      : paragraph(""),
    rule(),
    paragraph(
      text("A follow-up Review will validate the amendments. ", [{ type: "em" }]),
      text("(Generated by LawStack/aiops.)", [{ type: "em" }]),
    ),
  ]);

  try {
    const commentId = await ctx.jiraClient.postComment(task.jiraKey, body);
    audit({
      action: "jira.amend_comment_posted",
      taskId,
      runId,
      payload: { commentId, jiraKey: task.jiraKey, priorVerdict },
    });
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn("[jira] amend comment failed", {
      runId,
      taskId,
      error: (err as Error).message,
    });
    audit({
      action: "jira.amend_comment_failed",
      taskId,
      runId,
      payload: { error: (err as Error).message },
    });
  }
}

/** Helper used by spawnAgent.finalize to decide if a completed run was
 *  an amendment run (Plan started with amendFromReview=true). Looks at the
 *  audit_log for this run's `run.started_request` payload. */
export function wasAmendmentRun(runId: string): boolean {
  const row = db
    .select({ payloadJson: auditLog.payloadJson })
    .from(auditLog)
    .where(
      and(eq(auditLog.runId, runId), eq(auditLog.action, "run.started_request")),
    )
    .limit(1)
    .get();
  if (!row?.payloadJson) return false;
  try {
    const p = JSON.parse(row.payloadJson) as { amendFromReview?: boolean };
    return p.amendFromReview === true;
  } catch {
    return false;
  }
}
